/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    GlowCard: typeof import('./components/GlowCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheBg: typeof import('./components/TheBg.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheFriendFormat: typeof import('./components/TheFriendFormat.md')['default']
    TheGoBack: typeof import('./components/TheGoBack.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TheHitokoto: typeof import('./components/TheHitokoto.vue')['default']
    ThePosts: typeof import('./components/ThePosts.vue')['default']
    ThePostWrapper: typeof import('./components/ThePostWrapper.vue')['default']
    TheTech: typeof import('./components/TheTech.vue')['default']
    TheValine: typeof import('./components/TheValine.vue')['default']
  }
}
